package Wiring;

public enum Topics {
    UI_HALL_CALL_UP,
    UI_HALL_CALL_DOWN,
    UI_CABIN_SELECT,
    UI_FIRE_TOGGLED,
    CTRL_CMD_MOVE_TO,
    CTRL_CMD_DOOR_OPEN,
    CTRL_CMD_DOOR_CLOSE,
    SIM_FLOOR_TICK,
    SIM_ARRIVED,
    CTRL_STATE_UPDATE
}
