package Wiring;

public enum Topics {
    UI_HALL_CALL_UP,
    UI_HALL_CALL_DOWN,
    UI_CABIN_SELECT,
    UI_FIRE_TOGGLED,
    CTRL_CMD_MOVE_TO,
    SIM_FLOOR_TICK,
    SIM_ARRIVED,
    CTRL_CMD_STOP,
    UI_OVERLOAD_TOGGLED,
    UI_OBSTRUCT_TOGGLED;
}
